{% set name = "quill" %}
{% set version = "4.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/odygrd/quill/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c5e0c829096f81364fd55ac1358fe72b27785839474caa9c904b12a9e95c0e88
  patches:
    - patches/fix.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]

test:
  commands:
    - test -d ${PREFIX}/include/quill  # [unix]
    - test -f ${PREFIX}/include/quill/Frontend.h  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\quill\Frontend.h (exit 1)  # [win]

about:
  home: https://github.com/odygrd/quill
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Asynchronous Low Latency C++ Logging Library'
  description: |
    Quill is a high-performance, cross-platform asynchronous logging library 
    designed for C++17 and onwards
  doc_url: https://quillcpp.readthedocs.io/en/latest/
  dev_url: https://github.com/odygrd/quill

extra:
  recipe-maintainers:
    - odygrd
