{% set name = "quill" %}
{% set version = "4.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/odygrd/quill/archive/refs/tags/v{{ version }}.tar.gz
  sha256: be166da93210df53aab34ece1bddd14b08506588186723b504ffeeec651bbf7c
  patches:
    - patches/fix.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]

test:
  commands:
    - test -d ${PREFIX}/include/quill  # [unix]
    - test -f ${PREFIX}/include/quill/Frontend.h  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\quill\Frontend.h (exit 1)  # [win]

about:
  home: https://github.com/odygrd/quill
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Asynchronous Low Latency C++ Logging Library'
  description: |
    Quill is a high-performance, cross-platform asynchronous logging library 
    designed for C++17 and onwards
  doc_url: https://quillcpp.readthedocs.io/en/latest/
  dev_url: https://github.com/odygrd/quill

extra:
  recipe-maintainers:
    - odygrd
